feat(origin): set to optional
manchenkoff/nuxt-auth-sanctum pull request #18
Opened 2024-01-01 10:07 UTC by TartanLeGrand

# Overview 🌐
This PR introduces a significant enhancement to our Nuxt project by making the configuration of the **origin** property optional. This change leverages the capabilities of Nuxt's **useRequestUrl** from the [Nuxt Documentation](https://nuxt.com/docs/api/composables/use-request-url) to dynamically determine the origin URL. This update aims to streamline configuration and improve the flexibility of our application.

# Changes 🛠️

- **Optional Origin Configuration**: The origin configuration in our Nuxt setup has been modified to be optional. This change is intended to reduce the manual setup required and make our application more adaptive to different environments.

- **Dynamic Origin Retrieval**: Integrated Nuxt's useRequestUrl to automatically fetch the origin URL. This approach ensures that our application can dynamically adjust to the environment it is running in, whether in development, staging, or production.

# Implementation Details 📝
- Modified the configuration file to check if the origin is provided. If not, **useRequestUrl** is utilized to derive the origin.
- Ensured backward compatibility so that existing configurations with a defined **origin** continue to function seamlessly.
- Added relevant unit tests to cover the new scenarios introduced by these changes.

# How to Test 🧪

- **With Origin Configured:** Set up the application with the origin configured and ensure the application behaves as expected.
- **Without Origin Configured**: Remove the origin configuration and observe if the application correctly determines the origin using useRequestUrl.

# Benefits ✨

- **Simplicity**: Reduces the complexity of initial setup and configuration.
- **Flexibility**: Increases the adaptability of our application across different environments.
- **Maintenance**: Eases future maintenance by relying on built-in Nuxt functionality.

# Request for Comments 🗣️
I encourage the team to review these changes and provide feedback. Any suggestions for further improvements or concerns are highly welcomed. Let's discuss how we can make this integration as smooth and beneficial as possible!

2024-01-01 12:50 UTC, manchenkoff requested changes
Hey @TartanLeGrand, thanks a lot for the contribution! Left some comments, pls take a look when you have time!

2024-01-01 12:50 UTC, manchenkoff commented on src/runtime/httpFactory.ts
> +    const url = useRequestURL();
probably, it would be better to check `options.origin` before doing this operation to slightly reduce the number of operations when it is not necessary.

2024-01-01 12:50 UTC, manchenkoff commented on src/runtime/httpFactory.ts
> +  }
please, apply code style and run linter on the new code since the current build is failing

2024-01-01 15:59 UTC, TartanLeGrand commented on src/runtime/httpFactory.ts
> +  }
The style code in the editor config is in 2 indent

2024-01-01 16:46 UTC, manchenkoff commented on src/runtime/httpFactory.ts
> +  }
Hh, I see, missed that because my IDE overwrites it by `prettier` rules. I've just updated `.editorconfig` in master to have proper config like for `prettier`, pls merge/rebase and re-run scripts to reformat and and run linter.

2024-01-01 18:58 UTC, manchenkoff commented
There is still some formatting issue during the build, @TartanLeGrand could you please run `yarn fmt` and `yarn lint` locally and fix the issue?

2024-01-01 19:11 UTC, TartanLeGrand commented
> There is still some formatting issue during the build, @TartanLeGrand could you please run `yarn fmt` and `yarn lint` locally and fix the issue?

It's good

2024-01-02 15:36 UTC, TartanLeGrand commented
@manchenkoff but the build still broken because you have an error on your main branch. The types are not resolve.

2024-01-02 15:55 UTC, manchenkoff commented
Hey @TartanLeGrand, it's not in main branch, here is the [latest build](https://github.com/manchenkoff/nuxt-auth-sanctum/actions/runs/7387737703/job/20097082676). Build here is complaining about your changes with `origin` type

2024-01-02 16:05 UTC, TartanLeGrand commented
Hello, no. Have try on your main branch :smile: 
![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/56931733/5b7e747b-8ca1-415d-beb1-c1eb36001116)

2024-01-02 16:38 UTC, manchenkoff commented
I assume it's because of the line 57 since you use `origin` which is now `string | nullish` instead of `string | undefined`.

2024-01-22 22:07 UTC, closed without merging

2024-01-22 22:44 UTC, manchenkoff commented
@TartanLeGrand thanks again 👍 merged and published as v0.0.16