feat: add option to prepend the global middleware
manchenkoff/nuxt-auth-sanctum pull request #203
Opened 2024-10-13 09:20 UTC by jonian

Middlewares from modules have lower order from the ones in the middleware folder. This is a problem if we want to run an auth related global middleware.

For example, we want to run `sanctum:auth:global` to check if the user is authenticated before running a global middleware to check if the user has the right permissions.

This adds support for prepending the `sanctum:auth:global` middleware to the list of existing middleware, more info [here](https://nuxt.com/docs/api/kit/pages#addroutemiddleware).

```js
globalMiddleware: {
  // Default value is false
  prepend: true,
},
```

2024-10-19 22:15 UTC, manchenkoff commented
Hey @jonian, thanks a lot for the contribution! Could you also update the options interface in `src/runtime/types/options.ts`?  Also, make sure you run `pnpm validate` before pushing your changes to check that code is valid.

2024-10-19 22:21 UTC, manchenkoff requested changes

2024-10-19 22:21 UTC, manchenkoff commented on src/module.ts
> +        prepend: sanctumConfig.globalMiddleware.prepend,
since we use `Partial<GlobalMiddlewareOptions>`, it would be nice to show warning if value is undefined

2024-10-27 08:42 UTC, jonian commented on src/module.ts
> +        prepend: sanctumConfig.globalMiddleware.prepend,
Not really sure what the required changes are here.

2024-10-27 08:45 UTC, jonian commented
@manchenkoff hello! Thank you for looking at this. I updated the options interface and run `pnpm validate` to make sure that code is valid.

2024-10-27 15:11 UTC, manchenkoff approved these changes

2024-10-27 15:11 UTC, manchenkoff commented on src/module.ts
> +        prepend: sanctumConfig.globalMiddleware.prepend,
I meant something like this between 46 and 47 lines

```typescript
if (sanctumConfig.globalMiddleware.prepend == undefined)
{
  logger.warn('globalMiddleware.prepend is undefined')
}
```

but this is optional, so not a blocker for this PR 👍

2024-10-27 15:13 UTC, manchenkoff commented
It will be merged and released as `0.5.1` later today

2024-10-28 01:14 UTC, merged