fix: use Nuxt `$fetch` type for client
manchenkoff/nuxt-auth-sanctum pull request #269
Opened 2024-12-21 23:22 UTC by IsraelOrtuno

**Is your PR related to a specific issue/feature? Please describe and mention issues.**

There is an issue where server routes aren't being type-hinted by the packages client as it's using the type of `$Fetch` from `ofetch` which doesn't seem to be enriched with Nuxt server routes type hinting features.

Before

```ts
const client = useSanctumClient()
client('') // No suggestion made
```

After

```ts
const client = useSanctumClient()
client('') // -> /api/test
```

This PR ensures that the client is typed just like Nuxt `$fetch` helper.

2024-12-22 20:11 UTC, manchenkoff requested changes
Hey @IsraelOrtuno, thanks for the contribution! I left a couple of questions to understand the purpose and your solution better, please reply once you have time!

P.S. The linter check is failing, you can check the details in the workflow

2024-12-22 20:11 UTC, manchenkoff commented on src/runtime/httpFactory.ts
> +  return $fetch.create(httpOptions) as typeof $fetch
technically, this `$fetch.create(...)` returns this - `create<T = DefaultT, R extends NitroFetchRequest = DefaultR>(defaults: FetchOptions): $Fetch<T, R>;`, not sure that it should be returned as something different

2024-12-22 20:11 UTC, manchenkoff commented on playground/server/api/test.get.ts
> +export default defineEventHandler((_event: H3Event) => {
as far as I understand, this endpoint will be available in your new fetch client as you mentioned in the description, however, what is the point of having this autocompletion if this client is used for external Laravel API and not the Nuxt server API? Correct me if I am missing something

2024-12-23 10:13 UTC, IsraelOrtuno commented
> Hey @IsraelOrtuno, thanks for the contribution! I left a couple of questions to understand the purpose and your solution better, please reply once you have time!
> 
> P.S. The linter check is failing, you can check the details in the workflow

Yeah, this PR does not make any sense. I realized of what you just said just after submitting it. It's pointless as the Laravel API would always be a separate app and no way to suggest any endpoint.

Thanks for the module!

2024-12-23 10:13 UTC, closed without merging